export type CareerCategory = {
  id: string;
  label: string;
  shortLabel: string;
  description: string;
  mark: string;
};

export type Agency = {
  id: string;
  name: string;
  shortName: string;
  portfolio: string;
  focus: string;
  categories: string[];
  url: string;
  securitySensitive?: boolean;
};

export const careerCategories: CareerCategory[] = [
  {
    id: "administration",
    label: "Administration and business support",
    shortLabel: "Administration",
    description: "Coordination, governance, records and executive support",
    mark: "AB",
  },
  {
    id: "finance",
    label: "Accounting and finance",
    shortLabel: "Finance",
    description: "Budgets, reporting, grants, audit and assurance",
    mark: "AF",
  },
  {
    id: "economics",
    label: "Economics and forecasting",
    shortLabel: "Economics",
    description: "Modelling, markets, taxation and cost-benefit analysis",
    mark: "EC",
  },
  {
    id: "data",
    label: "Data, statistics and research",
    shortLabel: "Data and research",
    description: "Analysis, surveys, evaluation and visualisation",
    mark: "DR",
  },
  {
    id: "technology",
    label: "Software, technology and AI",
    shortLabel: "Technology and AI",
    description: "Coding, cloud, automation, product and responsible AI",
    mark: "AI",
  },
  {
    id: "cyber",
    label: "Cybersecurity",
    shortLabel: "Cybersecurity",
    description: "Security operations, risk, response and awareness",
    mark: "CY",
  },
  {
    id: "design",
    label: "Design and digital services",
    shortLabel: "Design",
    description: "Service design, UX, accessibility and user research",
    mark: "DS",
  },
  {
    id: "policy",
    label: "Policy and strategic advice",
    shortLabel: "Policy",
    description: "Policy development, briefing and strategic planning",
    mark: "PS",
  },
  {
    id: "projects",
    label: "Programs and project delivery",
    shortLabel: "Programs and projects",
    description: "Delivery, change, assurance and benefits management",
    mark: "PP",
  },
  {
    id: "regulation",
    label: "Compliance, regulation and investigation",
    shortLabel: "Regulation",
    description: "Assessment, inspection, enforcement and fraud prevention",
    mark: "CR",
  },
  {
    id: "service",
    label: "Service delivery and public contact",
    shortLabel: "Service delivery",
    description: "Claims, case management, client and community support",
    mark: "SD",
  },
  {
    id: "communications",
    label: "Communications and community engagement",
    shortLabel: "Communications",
    description: "Public information, media, consultation and engagement",
    mark: "CE",
  },
  {
    id: "field",
    label: "Field and operational work",
    shortLabel: "Field work",
    description: "Elections, environment, emergencies and regional operations",
    mark: "FO",
  },
  {
    id: "science",
    label: "Science, environment and technical work",
    shortLabel: "Science",
    description: "Climate, agriculture, geology, engineering and spatial work",
    mark: "ST",
  },
  {
    id: "health",
    label: "Health and social policy",
    shortLabel: "Health and social",
    description: "Public health, disability, aged care and social research",
    mark: "HS",
  },
  {
    id: "legal",
    label: "Legal and parliamentary work",
    shortLabel: "Legal",
    description: "Legal services, legislation, tribunals and FOI",
    mark: "LP",
  },
  {
    id: "people",
    label: "People and organisational development",
    shortLabel: "People and HR",
    description: "Recruitment, learning, workplace relations and culture",
    mark: "HR",
  },
  {
    id: "information",
    label: "Intelligence and information management",
    shortLabel: "Information",
    description: "Analysis, archives, records and knowledge management",
    mark: "IM",
  },
  {
    id: "procurement",
    label: "Procurement and contract management",
    shortLabel: "Procurement",
    description: "Tendering, commercial advice and vendor management",
    mark: "PC",
  },
  {
    id: "trades",
    label: "Trades, facilities and logistics",
    shortLabel: "Trades and logistics",
    description: "Property, fleet, warehousing and technical maintenance",
    mark: "TL",
  },
];

export const agencies: Agency[] = [
  {
    id: "abs",
    name: "Australian Bureau of Statistics",
    shortName: "ABS",
    portfolio: "Treasury",
    focus: "Official statistics, Census, data services, research and public engagement",
    categories: ["data", "technology", "design", "communications", "field", "administration"],
    url: "https://www.abs.gov.au/about/abs-careers",
  },
  {
    id: "dta",
    name: "Digital Transformation Agency",
    shortName: "DTA",
    portfolio: "Finance",
    focus: "Digital government policy, service standards, assurance and whole-of-government capability",
    categories: ["technology", "design", "cyber", "policy", "projects", "procurement"],
    url: "https://www.dta.gov.au/about-us/work-us",
  },
  {
    id: "services-australia",
    name: "Services Australia",
    shortName: "Services Australia",
    portfolio: "Finance",
    focus: "Payments, health and social services delivered at national scale",
    categories: ["service", "technology", "design", "cyber", "data", "projects", "administration"],
    url: "https://www.servicesaustralia.gov.au/careers",
  },
  {
    id: "finance",
    name: "Department of Finance",
    shortName: "Finance",
    portfolio: "Finance",
    focus: "Public resources, budgeting, procurement, governance and government operations",
    categories: ["finance", "economics", "policy", "procurement", "data", "projects", "administration"],
    url: "https://www.finance.gov.au/about-us/careers-finance",
  },
  {
    id: "aec",
    name: "Australian Electoral Commission",
    shortName: "AEC",
    portfolio: "Finance",
    focus: "Federal elections, enrolment, public information and national field operations",
    categories: ["field", "service", "communications", "technology", "data", "projects", "administration"],
    url: "https://www.aec.gov.au/employment/",
  },
  {
    id: "treasury",
    name: "Department of the Treasury",
    shortName: "Treasury",
    portfolio: "Treasury",
    focus: "Economic, fiscal, market and social policy advice",
    categories: ["economics", "policy", "data", "finance", "legal", "communications"],
    url: "https://treasury.gov.au/the-department/recruitment-and-careers",
  },
  {
    id: "ato",
    name: "Australian Taxation Office",
    shortName: "ATO",
    portfolio: "Treasury",
    focus: "Tax and superannuation administration, service delivery, compliance and technology",
    categories: ["finance", "service", "regulation", "technology", "cyber", "data", "legal"],
    url: "https://www.ato.gov.au/about-ato/careers",
  },
  {
    id: "accc",
    name: "Australian Competition and Consumer Commission",
    shortName: "ACCC",
    portfolio: "Treasury",
    focus: "Competition, consumer protection, product safety and economic regulation",
    categories: ["regulation", "legal", "economics", "data", "policy", "communications"],
    url: "https://www.accc.gov.au/about-us/careers",
  },
  {
    id: "apra",
    name: "Australian Prudential Regulation Authority",
    shortName: "APRA",
    portfolio: "Treasury",
    focus: "Financial-system supervision, risk, data and prudential policy",
    categories: ["finance", "regulation", "economics", "data", "cyber", "policy"],
    url: "https://www.apra.gov.au/careers-apra",
  },
  {
    id: "asic",
    name: "Australian Securities and Investments Commission",
    shortName: "ASIC",
    portfolio: "Treasury",
    focus: "Corporate, markets, financial services and consumer-credit regulation",
    categories: ["finance", "regulation", "legal", "data", "technology", "cyber"],
    url: "https://careers.asic.gov.au/",
  },
  {
    id: "productivity-commission",
    name: "Productivity Commission",
    shortName: "Productivity Commission",
    portfolio: "Treasury",
    focus: "Independent economic, social and environmental research and advice",
    categories: ["economics", "data", "policy", "communications"],
    url: "https://www.pc.gov.au/about/careers",
  },
  {
    id: "home-affairs",
    name: "Department of Home Affairs",
    shortName: "Home Affairs",
    portfolio: "Home Affairs",
    focus: "Migration, borders, national security, cyber policy and emergency coordination",
    categories: ["policy", "cyber", "regulation", "service", "technology", "data", "field"],
    url: "https://www.homeaffairs.gov.au/about-us/careers",
    securitySensitive: true,
  },
  {
    id: "austrac",
    name: "Australian Transaction Reports and Analysis Centre",
    shortName: "AUSTRAC",
    portfolio: "Home Affairs",
    focus: "Financial intelligence and regulation to counter money laundering and serious crime",
    categories: ["regulation", "information", "data", "finance", "technology", "cyber"],
    url: "https://www.austrac.gov.au/about-us/work-us",
    securitySensitive: true,
  },
  {
    id: "nema",
    name: "National Emergency Management Agency",
    shortName: "NEMA",
    portfolio: "Home Affairs",
    focus: "National disaster preparedness, response, recovery and resilience",
    categories: ["field", "projects", "policy", "communications", "data", "service"],
    url: "https://www.nema.gov.au/about-us/careers",
  },
  {
    id: "afp",
    name: "Australian Federal Police",
    shortName: "AFP",
    portfolio: "Home Affairs",
    focus: "Federal policing, investigations, intelligence and protective services",
    categories: ["regulation", "information", "cyber", "technology", "field", "legal"],
    url: "https://jobs.afp.gov.au/",
    securitySensitive: true,
  },
  {
    id: "asd",
    name: "Australian Signals Directorate",
    shortName: "ASD",
    portfolio: "Defence",
    focus: "Foreign signals intelligence, cybersecurity and offensive cyber operations",
    categories: ["cyber", "technology", "information", "data", "science"],
    url: "https://www.asd.gov.au/careers",
    securitySensitive: true,
  },
  {
    id: "defence",
    name: "Department of Defence",
    shortName: "Defence",
    portfolio: "Defence",
    focus: "Defence policy, capability, science, engineering, technology and operations",
    categories: ["technology", "cyber", "science", "projects", "procurement", "trades", "policy"],
    url: "https://www.defence.gov.au/jobs-careers",
    securitySensitive: true,
  },
  {
    id: "agriculture",
    name: "Department of Agriculture, Fisheries and Forestry",
    shortName: "Agriculture",
    portfolio: "Agriculture, Fisheries and Forestry",
    focus: "Biosecurity, trade, agriculture, fisheries, forestry and regional industries",
    categories: ["field", "science", "regulation", "policy", "data", "service"],
    url: "https://www.agriculture.gov.au/about/jobs",
  },
  {
    id: "dcceew",
    name: "Department of Climate Change, Energy, the Environment and Water",
    shortName: "DCCEEW",
    portfolio: "Climate Change, Energy, the Environment and Water",
    focus: "Climate, energy, environment, heritage, water and protected areas",
    categories: ["science", "field", "economics", "policy", "data", "projects"],
    url: "https://www.dcceew.gov.au/about/jobs",
  },
  {
    id: "bom",
    name: "Bureau of Meteorology",
    shortName: "Bureau of Meteorology",
    portfolio: "Climate Change, Energy, the Environment and Water",
    focus: "Weather, climate, water, space weather and environmental information",
    categories: ["science", "data", "technology", "field", "communications"],
    url: "https://www.bom.gov.au/careers/",
  },
  {
    id: "geoscience",
    name: "Geoscience Australia",
    shortName: "Geoscience Australia",
    portfolio: "Industry, Science and Resources",
    focus: "Earth science, hazards, resources, mapping and location information",
    categories: ["science", "data", "technology", "field"],
    url: "https://www.ga.gov.au/about/careers",
  },
  {
    id: "ip-australia",
    name: "IP Australia",
    shortName: "IP Australia",
    portfolio: "Industry, Science and Resources",
    focus: "Intellectual-property rights, examination, digital services and public information",
    categories: ["regulation", "technology", "design", "legal", "science", "service"],
    url: "https://www.ipaustralia.gov.au/about-us/careers",
  },
  {
    id: "health",
    name: "Department of Health, Disability and Ageing",
    shortName: "Health",
    portfolio: "Health, Disability and Ageing",
    focus: "National health, disability, aged-care policy, programs and regulation",
    categories: ["health", "policy", "data", "projects", "regulation", "communications"],
    url: "https://www.health.gov.au/about-us/work-with-us",
  },
  {
    id: "aihw",
    name: "Australian Institute of Health and Welfare",
    shortName: "AIHW",
    portfolio: "Health, Disability and Ageing",
    focus: "Health and welfare data, statistics, research and reporting",
    categories: ["health", "data", "technology", "communications"],
    url: "https://www.aihw.gov.au/about-us/careers",
  },
  {
    id: "social-services",
    name: "Department of Social Services",
    shortName: "Social Services",
    portfolio: "Social Services",
    focus: "Social policy and programs for families, communities, disability and inclusion",
    categories: ["health", "policy", "data", "projects", "communications", "service"],
    url: "https://www.dss.gov.au/about-department/jobs-department",
  },
  {
    id: "niaa",
    name: "National Indigenous Australians Agency",
    shortName: "NIAA",
    portfolio: "Prime Minister and Cabinet",
    focus: "Policy, programs and partnerships with Aboriginal and Torres Strait Islander peoples",
    categories: ["communications", "policy", "field", "projects", "service", "data"],
    url: "https://www.niaa.gov.au/who-we-are/careers",
  },
  {
    id: "dewr",
    name: "Department of Employment and Workplace Relations",
    shortName: "DEWR",
    portfolio: "Employment and Workplace Relations",
    focus: "Employment, skills, workplace relations and labour-market policy",
    categories: ["policy", "economics", "data", "projects", "regulation", "service"],
    url: "https://www.dewr.gov.au/about-department/work-us",
  },
  {
    id: "fwo",
    name: "Fair Work Ombudsman",
    shortName: "Fair Work Ombudsman",
    portfolio: "Employment and Workplace Relations",
    focus: "Workplace information, assistance, compliance and enforcement",
    categories: ["regulation", "legal", "service", "communications", "data"],
    url: "https://www.fairwork.gov.au/about-us/careers",
  },
  {
    id: "education",
    name: "Department of Education",
    shortName: "Education",
    portfolio: "Education",
    focus: "Early learning, schools, higher education, research and international education",
    categories: ["policy", "data", "projects", "communications", "service", "finance"],
    url: "https://www.education.gov.au/about-department/jobs-department",
  },
  {
    id: "dfat",
    name: "Department of Foreign Affairs and Trade",
    shortName: "DFAT",
    portfolio: "Foreign Affairs and Trade",
    focus: "Foreign policy, trade, development, consular services and international engagement",
    categories: ["policy", "economics", "communications", "service", "legal", "projects"],
    url: "https://www.dfat.gov.au/careers",
    securitySensitive: true,
  },
  {
    id: "infrastructure",
    name: "Department of Infrastructure, Transport, Regional Development, Communications, Sport and the Arts",
    shortName: "Infrastructure",
    portfolio: "Infrastructure, Transport, Regional Development, Communications, Sport and the Arts",
    focus: "Infrastructure, transport, regions, communications, arts and sport",
    categories: ["policy", "projects", "science", "economics", "communications", "regulation"],
    url: "https://www.infrastructure.gov.au/department/careers",
  },
  {
    id: "acma",
    name: "Australian Communications and Media Authority",
    shortName: "ACMA",
    portfolio: "Infrastructure, Transport, Regional Development, Communications, Sport and the Arts",
    focus: "Communications and media regulation, spectrum and online safety functions",
    categories: ["regulation", "technology", "legal", "data", "communications"],
    url: "https://www.acma.gov.au/careers-acma",
  },
  {
    id: "national-archives",
    name: "National Archives of Australia",
    shortName: "National Archives",
    portfolio: "Infrastructure, Transport, Regional Development, Communications, Sport and the Arts",
    focus: "Government records, archives, preservation, access and digital collections",
    categories: ["information", "technology", "communications", "administration", "design"],
    url: "https://www.naa.gov.au/about-us/employment",
  },
  {
    id: "dva",
    name: "Department of Veterans' Affairs",
    shortName: "Veterans' Affairs",
    portfolio: "Defence",
    focus: "Services, compensation, health and commemoration for veterans and families",
    categories: ["service", "health", "policy", "data", "technology", "communications"],
    url: "https://www.dva.gov.au/about/overview/jobs-dva",
  },
  {
    id: "oaic",
    name: "Office of the Australian Information Commissioner",
    shortName: "OAIC",
    portfolio: "Attorney-General's",
    focus: "Privacy, freedom of information and information-policy regulation",
    categories: ["legal", "regulation", "policy", "technology", "communications"],
    url: "https://www.oaic.gov.au/about-the-OAIC/careers",
  },
];

export const agencyById = Object.fromEntries(
  agencies.map((agency) => [agency.id, agency]),
) as Record<string, Agency>;

export const categoryById = Object.fromEntries(
  careerCategories.map((category) => [category.id, category]),
) as Record<string, CareerCategory>;
